name = "fleet-gps-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
GPS_SERVER = "console.onefleet.hk"
GPS_VIDEO_PORT = "6604"
GPS_ADMIN_ACCOUNT = "admin"
GPS_ADMIN_PASSWORD_MD5 = "4FF4C011268967DF32B6253CA0E7BDF0"